BSE_NSE_companies = ["BF Utilities Limited","OK Play India Limited"]

SME_companies = [
    "ABS Marine Services Limited",
    "Accent Microcell Limited",
    "Addictive Learning Technology Limited",
    "Aditya Ultra Steel Limited",
    "Aeron Composite Limited",
    "Aesthetik Engineers Limited",
    "Aimtron Electronics Limited",
    "Akiko Global Services Limited",
    "All E Technologies Limited",
    "Aluwind Architectural Limited",
    "Ambey Laboratories Limited",
    "Amiable Logistics (India) Limited",
    "ANI Integrated Services Limited",
    "Aprameya Engineering Limited",
    "Ashapura Logistics Limited",
    "Aspire & Innovative Advertising Limited",
    "Avi Ansh Textile Limited",
    "AVP Infracon Limited",
    "AVSL Industries Limited",
    "Baheti Recycling Industries Limited",
    "Beacon Trusteeship Limited",
    "BEW Engineering Limited",
    "Bikewo Green Tech Limited",
    "Boss Packaging Solutions Limited",
    "Brace Port Logistics Limited",
    "Bulkcorp International Limited",
    "Chavda Infra Limited",
    "Chetana Education Limited",
    "Cyber Media Research & Services Limited",
    "Danish Power Limited",
    "Deccan Transcon Leasing Limited",
    "Dhariwalcorp Limited",
    "Diensten Tech Limited",
    "Divine Power Energy Limited",
    "Divyadhan Recycling Industries Limited",
    "Drone Destination Limited",
    "Durlax Top Surface Limited",
    "E Factor Experiences Limited",
    "Effwa Infra & Research Limited",
    "Emkay Taps and Cutting Tools Limited",
    "Enser Communications Limited",
    "Envirotech Systems Limited",
    "Esprit Stones Limited",
    "Euro Panel Products Limited",
    "Excellent Wires and Packaging Limited",
    "Falcon Technoprojects India Limited",
    "Forcas Studio Limited",
    "Forge Auto International Limited",
    "Freshara Agro Exports Limited",
    "Frog Cellsat Limited",
    "Gajanand International Limited",
    "Ganesh Green Bharat Limited",
    "Goldkart Jewels Limited",
    "GP Eco Solutions India Limited",
    "Greenchef Appliances Limited",
    "GSM Foils Limited",
    "Hoac Foods India Limited",
    "Homesfy Realty Limited",
    "HVAX Technologies Limited",
    "Ideal Technoplast Industries Limited",
    "Indian Emulsifiers Limited",
    "Indian Phosphate Limited",
    "Innomet Advanced Materials Limited",
    "Jay Bee Laminations Limited",
    "Jeyyam Global Foods Limited",
    "Kalana Ispat Limited",
    "Kataria Industries Limited",
    "Kaushalya Logistics Limited",
    "Konstelec Engineers Limited",
    "Kotyark Industries Limited",
    "Krishna Defence and Allied Industries Limited",
    "Lakshya Powertech Limited",
    "Lloyds Luxuries Limited",
    "Macobs Technologies Limited",
    "Madhusudan Masala Limited",
    "Mangalam Worldwide Limited",
    "Manglam Infra & Engineering Limited",
    "Mason Infratech Limited",
    "Medicamen Organics Limited",
    "Megatherm Induction Limited",
    "My Mudra Fincorp Limited",
    "Namo eWaste Management Limited",
    "Nephro Care India Limited",
    "OBSC Perfection Limited",
    "Oriana Power Limited",
    "Osel Devices Limited",
    "P. E. Analytics Limited",
    "Paramatrix Technologies Limited",
    "Paramount Dye Tec Limited",
    "Paramount Speciality Forgings Limited",
    "Pelatro Limited",
    "Petro Carbon and Chemicals Limited",
    "Phantom Digital Effects Limited",
    "Phoenix Overseas Limited",
    "Picturepost Studios Limited",
    "Positron Energy Limited",
    "Pramara Promotions Limited",
    "Pranik Logistics Limited",
    "Pratham EPC Projects Limited",
    "Premium Plast Limited",
    "Prizor Viztech Limited",
    "Pulz Electronics Limited",
    "Quest Laboratories Limited",
    "QVC Exports Limited",
    "Rajgor Castor Derivatives Limited",
    "Rajputana Industries Limited",
    "Rappid Valves (India) Limited",
    "Remus Pharmaceuticals Limited",
    "RNFI Services Limited",
    "Rockingdeals Circular Economy Limited",
    "Rulka Electricals Limited",
    "S A Tech Software India Limited",
    "S D Retail Limited",
    "Sadhav Shipping Limited",
    "Sahaj Solar Limited",
    "Sahana System Limited",
    "Sahasra Electronic Solutions Limited",
    "Saj Hotels Limited",
    "Sar Televenture Limited",
    "Sathlokhar Synergys E&C Global Limited",
    "Sati Poly Plast Limited",
    "Shivalic Power Control Limited",
    "Shree Karni Fabcom Limited",
    "Shree OSFM E-Mobility Limited",
    "Shubhshree Biofuels Energy Limited",
    "Slone Infosystems Limited",
    "Solex Energy Limited",
    "Solve Plastic Products Limited",
    "Sona Machinery Limited",
    "SPP Polymer Limited",
    "Srivari Spices And Foods Limited",
    "Sunlite Recycling Industries Limited",
    "Sylvan Plyboard (India) Limited",
    "Systango Technologies Limited",
    "TBI Corn Limited",
    "TechEra Engineering (India) Limited",
    "Teerth Gopicon Limited",
    "Thinking Hats Entertainment Solutions Limited",
    "Trident Techlabs Limited",
    "Tridhya Tech Limited",
    "Trom Industries Limited",
    "Tunwal E-Motors Limited",
    "Unihealth Consultancy Limited",
    "Unilex Colours and Chemicals Limited",
    "United Heat Transfer Limited",
    "Urban Enviro Waste Management Limited",
    "Usha Financial Services Limited",
    "Utssav CZ Gold Jewels Limited",
    "V.L.Infraprojects Limited",
    "Vasa Denticity Limited",
    "Vdeal System Limited",
    "Veritaas Advertising Limited",
    "Vilas Transcore Limited",
    "Vinyas Innovative Technologies Limited",
    "Visaman Global Sales Limited",
    "Vishwas Agri Seeds Limited",
    "Vision Infra Equipment Solutions Limited",
    "Winny Immigration & Education Services Limited",
    "Wise Travel India Limited",
    "Wol 3D India Limited"
]